README.md
package.json
src/actorDefinition.ts
src/const.ts
src/examples/client_sse.py
src/main.ts
src/server.ts
src/types.ts

- Handle server readiness probe
- Add Origin/mcp-server to user-agent
- Truncate inputSchema description to 200 characters. Limit enums to 50 values.

feat: Truncate input schema, limit description to 200 characters

---

src/actors.ts
src/types.ts
tests/actors-test.ts

related to part of this issue https://github.com/apify/actors-mcp-server/issues/36
Updated `filterSchemaProperties` in `src/actors.ts` to handle array types by guessing `items.type` from `items.type`, `prefill`, `default`, or `editor`. Added `items` and `editor` to `SchemaProperties` in `src/types.ts`.

feat: tool-items-type

---

eslint.config.mjs
src/actors.ts
src/server.ts
src/types.ts

mastra.ai agent failed to run WCC because of the nested properties, the object input properties: had to infer their schema based on the editor provided; This helps the agent to call the WCC with the correct options.

fix: tool schema array type infer and nested props

---

README.md

fix: Update README for a localhost configuration

---

README.md

closes https://github.com/apify/actors-mcp-server/issues/43

docs: document input schema processing

---

src/const.ts
src/tools/helpers.ts
src/tools/index.ts
src/tools/store_collection.ts
tests/actor-server-test.ts

fix: Update search tool description

---

package-lock.json
package.json
src/actor/server.ts
src/mcp/server.ts

chore: bump mcp-sdk version to 1.10.0

---

src/input.ts
src/main.ts

Context: https://console.apify.com/actors/1lSvMAaRcadrM1Vgv/issues/WYN8ihB6nRJayIwMR
Closes: #88

fix: load actors as tools dynamically based on input

---

src/const.ts
src/tools/build.ts
src/tools/helpers.ts
src/tools/store_collection.ts
tests/actor-server-test.ts

Closes https://github.com/apify/actors-mcp-server/issues/98

fix: rename tools

---

src/examples/clientStdio.ts
src/examples/clientStreamableHttp.ts

fix: stdio and streamable http client examples

---

src/const.ts
src/mcp/server.ts
src/tools/helpers.ts
tests/integration/actor.server.test.ts

This PR adds `help-tool` that returns a simple guide on how to use and troubleshoot issues with Apify MCP server

feat: add help tool

---

README.md

fix: Update README with a link to a blog post

---

src/mcp/server.ts

Allow disabling of `process.on` SIGINT handler to prevent max listeners warning when spawning multiple instances of `ActorsMcpServer`

fix: apify-mcp-server max listeners warning

---

src/tools/actor.ts
src/tools/utils.ts
src/types.ts

this should fix the Ajv memory leak, tested locally with MCP stress tester swarm mode - the memory stays consistently around 170 MB
closes https://github.com/apify/apify-mcp-server/issues/56

fix: ajv compile memory leak

---

src/actor/server.ts
src/mcp/server.ts
src/tools/helpers.ts
src/types.ts
tests/integration/suite.ts

Use MCP request handler extras for notification sending - this is needed so streamable POST SSE notifications work correctly. Also fixes notifications in streamable transport for the standby Actor mode which were not working - this needs POST SSE but it should be safe because the SSE sessions are usually short-lived until all tool call or other requests are finished and then new is created for each POST request.
prerequisite to https://github.com/apify/apify-mcp-server/pull/69
related to https://github.com/apify/apify-mcp-server/issues/64

fix: notifications

---

.actor/input_schema.json
src/input.ts
src/mcp/server.ts
src/stdio.ts
tests/helpers.ts
tests/integration/suite.ts
tests/unit/input.test.ts

closes https://github.com/apify/actors-mcp-server/issues/144

feat: dynamic actor loading is enabled by default

---

src/const.ts
src/mcp/server.ts
src/tools/actor.ts
src/tools/helpers.ts
src/tools/index.ts
tests/integration/suite.ts

closes #155
Generic tool for calling Actors dynamically, for clients without support for the dynamic tools list.
TODO:

feat: call-actor tool

---

README.md
package-lock.json
package.json
src/const.ts
src/state.ts
src/tools/fetch-apify-docs.ts
src/tools/index.ts
src/tools/search-apify-docs.ts
src/types.ts
src/utils/apify-docs.ts
src/utils/html-to-md.ts
src/utils/turndown.ts
tests/integration/suite.ts

Changes:
- added Apify docs search and fetch tools
- updated README
closes https://github.com/apify/ai-team/issues/39

feat: apify docs tools

---

src/actor/server.ts
src/input.ts
src/mcp/server.ts
src/mcp/utils.ts
src/stdio.ts
src/tools/index.ts
src/tools/run.ts
src/types.ts
src/utils/tools-loader.ts
tests/helpers.ts
tests/integration/suite.ts
tests/unit/input.test.ts

closes https://github.com/apify/actors-mcp-server/issues/166
**Only `docs` tools category is currently enabled by default (always)**
This PR introduces the `tools` (`--tools` or `?tools`) comma separated list param so users can choose which tools are loaded into their MCP session.
Possible values:
- docs: Search and fetch Apify documentation tools.
- runs: Get Actor runs list, run details, and logs from a specific Actor run.
- storage: Access datasets, key-value stores, and their records.
Example:
```
--tools docs,runs
?tools=docs,storage
```
Also vibe refactored the tool loading logic so it's not duplicated in the `stdio.ts`

feat: add tool selection by feature param

---

src/const.ts
src/main.ts
src/mcp/server.ts
src/tools/actor.ts
src/types.ts
src/utils/progress.ts
tests/unit/utils.progress.test.ts

feat: progress notification

---

package.json
src/index-internals.ts

Export internals used in `apify-mcp-server` repo to prevent importing from `dist/`.
related to https://github.com/apify/apify-mcp-server/issues/102

fix: export internals for apify-mcp-server

---

src/tools/helpers.ts
tests/integration/suite.ts

Fix MCP behaviour when adding non existent Actor. Return no tool added message instead of that the non existent Actor was added.

fix: adding non existent Actor

---

package-lock.json
package.json
src/mcp/const.ts
src/mcp/server.ts

Implement https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging#setting-log-level so newer clients can connect without issues
closes https://github.com/apify/apify-mcp-server/issues/231

feat: implement mcp logging set level request handler

---

.github/workflows/release.yaml

closes https://github.com/apify/apify-mcp-server/issues/229
Added automatic version update also for the `manifest.json`. Also figured out we were accessing the new git committed ref with the `.json` updates incorrectly and it could cause we were releasing packages with wrong version number. Fixed this and also added checks to prevent this in future.

ci: auto set dxt version on release

---

README.md
src/tools/build.ts
src/utils/tools-loader.ts

Btw. I've decided to keep this log so that we know if someone is trying to use it.
```
log.warning('Tool category "preview" is deprecated');
```
close #252

fix: Handle deprecated tool preview

---

src/tools/actor.ts

Fixes https://github.com/apify/apify-mcp-server/issues/264
It was a simple issue, type JSON is not allowed, it must be text.

fix: error when content type is json

---

README.md
src/tools/actor.ts
src/tools/fetch-actor-details.ts
src/tools/store_collection.ts
src/utils/actor-card.ts
src/utils/pricing-info.ts

Return properly formatted Markdown for Actor search and for actor-details page
close: https://github.com/apify/apify-mcp-server/issues/286
```
- **Search query:** mcp server
- **Number of Actors found:** 5
- **URL:** https://apify.com/apify/actors-mcp-server
- **Developed by:** [apify](https://apify.com/apify) (Apify)
- **Description:** ⚠️ Legacy: This Actor is outdated. For the latest features and full documentation, visit https://mcp.apify.com. Easily connect any Apify Actor to AI agents using Anthropic’s Model Context Protocol (MCP) with our actively maintained MCP server.
- **Categories:** Open Source, Agents, MCP Servers
- **[Pricing](https://apify.com/apify/actors-mcp-server/pricing):** User pays for the computing resources consumed by the Actor
- **Stats:** 2,227 total users, 153 …
```

fix: Actor card markdown
